spring:
  application:
    name: nextstation
  profiles:
    active: local
  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          # SMTP 서버 응답 지연 시 요청 스레드가 무한 대기하지 않도록 타임아웃 지정
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 180000 # 이메일 인증번호 유효시간, 3분

logging:
  level:
    root: INFO
    com.cotato.nextstation: DEBUG

server:
  port: 8080