spring:
  application:
    name: nextstation
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update # validation으로 변경 필요
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.cotato.nextstation: DEBUG

server:
  port: 8080